<?php

/*
 * sync*gw RoundCube Bundle
 *
 *	@copyright	(c) 2008 - 2023 Florian Daeumling, Germany. All right reserved
 * 	@license 	https://github.com/Toteph42/syncgw/blob/master/LICENSE
 */

$labels['syncgw_p_title']   = 'Synchronisationseinstellungen';
$labels['syncgw_m_head']    = 'Mailbox mit sync&bull;gw synchronisieren';
$labels['syncgw_m_text']    = 'Alle Ordner';
$labels['syncgw_a_head']    = 'Adressbücher mit sync&bull;gw synchronisieren';
$labels['syncgw_x_text']    = 'Alle Adressbücher zusammenführen';
$labels['syncgw_a_tonly']   = 'Nur Kontakte mit Telefonnummern';
$labels['syncgw_c_head']    = 'Kalender mit sync&bull;gw synchronisieren';
$labels['syncgw_t_head']    = 'Aufgabenlisten mit sync&bull;gw synchronisieren';
$labels['syncgw_n_head']    = 'Notizen mit sync&bull;gw synchronisieren';
$labels['syncgw_n_text']    = 'Persönliche Notizen';

?>