<?php

/*
 * sync*gw RoundCube Bundle
 *
 *	@copyright	(c) 2008 - 2023 Florian Daeumling, Germany. All right reserved
 * 	@license 	https://github.com/Toteph42/syncgw/blob/master/LICENSE
 */

$labels['syncgw_p_title']   = 'Synchronization settings';
$labels['syncgw_m_head']    = 'Synchronize mail box with sync&bull;gw';
$labels['syncgw_m_text']    = 'All folder';
$labels['syncgw_a_head']    = 'Synchronize address book with sync&bull;gw';
$labels['syncgw_x_text']	= 'Merge add address books';
$labels['syncgw_a_tonly']   = 'Only contacts with phone numbers';
$labels['syncgw_c_head']    = 'Synchronize calendar with sync&bull;gw';
$labels['syncgw_t_head']    = 'Synchronize task list with sync&bull;gw';
$labels['syncgw_n_head']    = 'Synchronize notes with sync&bull;gw';
$labels['syncgw_n_text']    = 'Personal notes';

?>